import fs from 'fs';
import path from 'path';
import { HealthScore } from '../types/index.js';
import { validateOutputPath } from '../utils/security.js';

export interface ReadmeUpdateResult {
  updated: boolean;
  method: 'badge-line' | 'html-comment' | 'appended' | 'no-readme';
  previousContent?: string;
}

export function findReadmePath(rootDir: string): string | null {
  const candidates = ['README.md', 'readme.md', 'README.MD', 'Readme.md'];
  for (const name of candidates) {
    const fullPath = path.join(rootDir, name);
    if (fs.existsSync(fullPath)) {
      return fullPath;
    }
  }
  return null;
}

export function updateReadmeBadge(rootDir: string, health: HealthScore): ReadmeUpdateResult {
  const readmePath = findReadmePath(rootDir);

  if (!readmePath) {
    return { updated: false, method: 'no-readme' };
  }

  const previousContent = fs.readFileSync(readmePath, 'utf-8');
  const badgeLine = `![Codebase Health](.roast-badge.svg) <!-- score: ${health.score}/100 ${health.grade} ${health.label} -->`;

  // Method 2: HTML comment block (check before line-based to handle block replacements)
  const blockPattern = /<!-- roast-score-start -->[\s\S]*?<!-- roast-score-end -->/;
  if (blockPattern.test(previousContent)) {
    const replacement = `<!-- roast-score-start -->\n${badgeLine}\n<!-- roast-score-end -->`;
    const newContent = previousContent.replace(blockPattern, replacement);
    validateOutputPath(rootDir, path.relative(rootDir, readmePath));
    fs.writeFileSync(readmePath, newContent, 'utf-8');
    return { updated: true, method: 'html-comment', previousContent };
  }

  // Method 1: Update existing roast badge line
  const lines = previousContent.split('\n');
  const badgeLineIndex = lines.findIndex((line) => {
    return (
      line.includes('![Codebase Health](.roast-badge.svg)') ||
      (line.includes('![Health](') && line.includes('.roast-badge.svg')) ||
      line.includes('<!-- roast-badge -->')
    );
  });

  if (badgeLineIndex !== -1) {
    lines[badgeLineIndex] = badgeLine;
    const newContent = lines.join('\n');
    validateOutputPath(rootDir, path.relative(rootDir, readmePath));
    fs.writeFileSync(readmePath, newContent, 'utf-8');
    return { updated: true, method: 'badge-line', previousContent };
  }

  // Method 3: Append to README
  const appendBlock = `\n<!-- roast-score-start -->\n## Code Health\n\n${badgeLine}\n\nGenerated by [roast-my-codebase](https://github.com/rahuldk1105/roast-my-codebase)\n<!-- roast-score-end -->`;
  const newContent = previousContent + appendBlock;
  validateOutputPath(rootDir, path.relative(rootDir, readmePath));
  fs.writeFileSync(readmePath, newContent, 'utf-8');
  return { updated: true, method: 'appended', previousContent };
}
