import { describe, it, expect } from "vitest";
import { renderMarkdownReport } from "../src/report/markdown.js";
import { RoastReport, Finding, Roast, FixSuggestion } from "../src/types/index.js";

describe("Markdown Formatter", () => {
  const mockStats = {
    totalFiles: 512,
    sourceFiles: 247,
    totalLines: 14203,
    largestFiles: [],
    dependencies: 42,
    devDependencies: 28,
  };

  const mockHealth = {
    score: 68,
    grade: "C",
    label: "Needs Work",
  };

  describe("renderMarkdownReport", () => {
    it("should render a complete markdown report with all sections", () => {
      const findings: Finding[] = [
        {
          id: "1",
          severity: "critical",
          category: "Large Files",
          message: "File has 1,847 lines",
          file: "src/utils/monster.ts",
        },
        {
          id: "2",
          severity: "warning",
          category: "Complexity",
          message: "Function 'processData' has complexity 42",
        },
        {
          id: "3",
          severity: "info",
          category: "TODOs",
          message: "Found 12 TODO comments",
        },
      ];

      const roasts: Roast[] = [
        {
          target: "node_modules",
          message: "You have 847 dependencies. Is this a codebase or a dependency collector's convention?",
          category: "Dependencies",
        },
      ];

      const fixes: FixSuggestion[] = [
        {
          finding: findings[0],
          suggestion: "Break this file into smaller modules (< 500 lines each)",
        },
      ];

      const report: RoastReport = {
        projectName: "test-project",
        stats: mockStats,
        health: mockHealth,
        findings,
        roasts,
        verdict: "Your codebase needs some work, but there's hope!",
        fixes,
      };

      const markdown = renderMarkdownReport(report);

      // Check header
      expect(markdown).toContain("# 🔥 Roast Report: test\\-project");

      // Check health score
      expect(markdown).toContain("## Health Score: 68/100 (C)");
      expect(markdown).toContain("68/100");

      // Check stats table
      expect(markdown).toContain("## Project Summary");
      expect(markdown).toContain("| Files Scanned | 247 |");
      expect(markdown).toContain("| Total Files | 512 |");
      expect(markdown).toContain("| Lines of Code | 14,203 |");
      expect(markdown).toContain("| Dependencies | 42 |");
      expect(markdown).toContain("| Dev Dependencies | 28 |");

      // Check findings sections
      expect(markdown).toContain("## Findings");
      expect(markdown).toContain("### 🔴 Critical (1)");
      expect(markdown).toContain("### ⚠️ Warnings (1)");
      expect(markdown).toContain("### ℹ️ Info (1)");

      // Check roasts
      expect(markdown).toContain("## 🔥 Roasts");
      expect(markdown).toContain("> **node\\_modules**");

      // Check fix suggestions
      expect(markdown).toContain("## 📝 Fix Suggestions");
      expect(markdown).toContain("Break this file into smaller modules");

      // Check verdict
      expect(markdown).toContain("## Verdict");
      expect(markdown).toContain("Your codebase needs some work");

      // Check footer
      expect(markdown).toContain("*Generated by [roast-my-codebase]");
    });

    it("should render collapsible details tags for findings", () => {
      const findings: Finding[] = [
        {
          id: "1",
          severity: "critical",
          category: "Security",
          message: "Potential security issue",
        },
      ];

      const report: RoastReport = {
        projectName: "test",
        stats: mockStats,
        health: mockHealth,
        findings,
        roasts: [],
        verdict: "Test verdict",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).toContain("<details>");
      expect(markdown).toContain("<summary>View critical issues</summary>");
      expect(markdown).toContain("</details>");
    });

    it("should keep info section open by default", () => {
      const findings: Finding[] = [
        {
          id: "1",
          severity: "info",
          category: "Info",
          message: "Some info",
        },
      ];

      const report: RoastReport = {
        projectName: "test",
        stats: mockStats,
        health: mockHealth,
        findings,
        roasts: [],
        verdict: "Test verdict",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).toContain('<details open>');
    });

    it("should handle empty findings gracefully", () => {
      const report: RoastReport = {
        projectName: "perfect-project",
        stats: mockStats,
        health: { score: 100, grade: "A+", label: "Excellent" },
        findings: [],
        roasts: [],
        verdict: "Perfect codebase!",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).toContain("## Findings");
      expect(markdown).toContain("No issues found! 🎉");
      expect(markdown).not.toContain("### 🔴 Critical");
      expect(markdown).not.toContain("### ⚠️ Warnings");
      expect(markdown).not.toContain("### ℹ️ Info");
    });

    it("should handle empty roasts", () => {
      const report: RoastReport = {
        projectName: "test",
        stats: mockStats,
        health: mockHealth,
        findings: [],
        roasts: [],
        verdict: "Test verdict",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).not.toContain("## 🔥 Roasts");
    });

    it("should handle missing fixes", () => {
      const report: RoastReport = {
        projectName: "test",
        stats: mockStats,
        health: mockHealth,
        findings: [],
        roasts: [],
        verdict: "Test verdict",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).not.toContain("## 📝 Fix Suggestions");
    });

    it("should escape special markdown characters", () => {
      const findings: Finding[] = [
        {
          id: "1",
          severity: "critical",
          category: "Test*Category",
          message: "Message with [brackets] and *asterisks* and `backticks`",
          file: "src/file_with_underscores.ts",
        },
      ];

      const report: RoastReport = {
        projectName: "test*project",
        stats: mockStats,
        health: mockHealth,
        findings,
        roasts: [],
        verdict: "Verdict with **bold** text",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).toContain("\\*");
      expect(markdown).toContain("\\[");
      expect(markdown).toContain("\\]");
    });

    it("should render health bar correctly", () => {
      const tests = [
        { score: 0, expected: "░".repeat(30) + " 0/100" },
        { score: 50, expected: "█".repeat(15) + "░".repeat(15) + " 50/100" },
        { score: 100, expected: "█".repeat(30) + " 100/100" },
      ];

      for (const test of tests) {
        const report: RoastReport = {
          projectName: "test",
          stats: mockStats,
          health: { score: test.score, grade: "A", label: "Test" },
          findings: [],
          roasts: [],
          verdict: "Test",
        };

        const markdown = renderMarkdownReport(report);
        expect(markdown).toContain(test.expected);
      }
    });

    it("should include file location in findings when present", () => {
      const findings: Finding[] = [
        {
          id: "1",
          severity: "warning",
          category: "Test",
          message: "Test message",
          file: "src/test.ts",
        },
      ];

      const report: RoastReport = {
        projectName: "test",
        stats: mockStats,
        health: mockHealth,
        findings,
        roasts: [],
        verdict: "Test",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).toContain("(src/test\\.ts)");
    });

    it("should format large numbers with commas", () => {
      const report: RoastReport = {
        projectName: "test",
        stats: {
          totalFiles: 1234,
          sourceFiles: 567,
          totalLines: 89012,
          largestFiles: [],
          dependencies: 345,
          devDependencies: 678,
        },
        health: mockHealth,
        findings: [],
        roasts: [],
        verdict: "Test",
      };

      const markdown = renderMarkdownReport(report);

      expect(markdown).toContain("1,234");
      expect(markdown).toContain("89,012");
    });
  });
});
