import fs from 'fs';
import { RoastReport } from '../types/index.js';

export function isGitHubActions(): boolean {
  return !!process.env.GITHUB_ACTIONS;
}

export function writeGitHubStepSummary(report: RoastReport): void {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryPath) return;

  const lines: string[] = [];

  // Header
  const scoreEmoji = report.health.score >= 80 ? '✅' : report.health.score >= 60 ? '⚠️' : '🔴';
  lines.push(`## 🔥 Roast My Codebase — ${report.projectName}`);
  lines.push('');
  lines.push(`${scoreEmoji} **Health Score: ${report.health.score}/100** — ${report.health.grade} — ${report.health.label}`);
  lines.push('');

  // Stats table
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Files | ${report.stats.sourceFiles.toLocaleString()} |`);
  lines.push(`| Lines of Code | ${report.stats.totalLines.toLocaleString()} |`);
  lines.push(`| Dependencies | ${report.stats.dependencies} |`);
  lines.push(`| Total Findings | ${report.findings.length} |`);
  lines.push('');

  // Findings by severity
  const criticals = report.findings.filter(f => f.severity === 'critical');
  const warnings = report.findings.filter(f => f.severity === 'warning');
  const infos = report.findings.filter(f => f.severity === 'info');

  if (criticals.length > 0 || warnings.length > 0) {
    lines.push('### Findings Summary');
    lines.push('');
    if (criticals.length > 0) lines.push(`- 🔴 **${criticals.length} critical**`);
    if (warnings.length > 0) lines.push(`- ⚠️ **${warnings.length} warnings**`);
    if (infos.length > 0) lines.push(`- ℹ️ ${infos.length} info`);
    lines.push('');
  }

  // Top findings table (up to 10)
  const topFindings = [...criticals, ...warnings].slice(0, 10);
  if (topFindings.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Top Findings</summary>');
    lines.push('');
    lines.push('| Severity | Category | Message | File |');
    lines.push('|----------|----------|---------|------|');
    for (const f of topFindings) {
      const icon = f.severity === 'critical' ? '🔴' : '⚠️';
      const msg = f.message.replace(/\|/g, '\\|').slice(0, 80);
      const file = (f.file || '—').replace(/\|/g, '\\|');
      lines.push(`| ${icon} ${f.severity} | ${f.category} | ${msg} | \`${file}\` |`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  // Verdict
  lines.push(`> *${report.verdict}*`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [roast-my-codebase](https://github.com/rahuldk1105/roast-my-codebase)*');

  try {
    fs.appendFileSync(summaryPath, lines.join('\n') + '\n');
  } catch {
    // Silently ignore if summary file is not writable
  }
}
