import { RoastReport, Finding } from "../types/index.js";

/**
 * Escapes special markdown characters in text to prevent formatting issues
 */
function escapeMarkdown(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\*/g, "\\*")
    .replace(/\_/g, "\\_")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/\#/g, "\\#")
    .replace(/\+/g, "\\+")
    .replace(/\-/g, "\\-")
    .replace(/\./g, "\\.")
    .replace(/\!/g, "\\!")
    .replace(/\|/g, "\\|");
}

/**
 * Renders a markdown health bar with filled and empty blocks
 */
function renderMarkdownHealthBar(score: number): string {
  const width = 30;
  const filled = Math.round((score / 100) * width);
  const empty = width - filled;
  return "█".repeat(filled) + "░".repeat(empty) + ` ${score}/100`;
}

/**
 * Renders findings organized by severity with collapsible sections
 */
function renderMarkdownFindings(findings: Finding[]): string {
  const sections: string[] = ["## Findings\n"];

  const criticals = findings.filter((f) => f.severity === "critical");
  const warnings = findings.filter((f) => f.severity === "warning");
  const infos = findings.filter((f) => f.severity === "info");

  if (criticals.length === 0 && warnings.length === 0 && infos.length === 0) {
    sections.push("No issues found! 🎉\n");
    return sections.join("\n");
  }

  if (criticals.length > 0) {
    sections.push(`### 🔴 Critical (${criticals.length})`);
    sections.push("<details>");
    sections.push("<summary>View critical issues</summary>\n");
    for (const f of criticals) {
      const location = f.file ? ` (${escapeMarkdown(f.file)})` : "";
      sections.push(`- **${escapeMarkdown(f.category)}** - ${escapeMarkdown(f.message)}${location}`);
    }
    sections.push("\n</details>\n");
  }

  if (warnings.length > 0) {
    sections.push(`### ⚠️ Warnings (${warnings.length})`);
    sections.push("<details>");
    sections.push("<summary>View warnings</summary>\n");
    for (const f of warnings) {
      const location = f.file ? ` (${escapeMarkdown(f.file)})` : "";
      sections.push(`- **${escapeMarkdown(f.category)}** - ${escapeMarkdown(f.message)}${location}`);
    }
    sections.push("\n</details>\n");
  }

  if (infos.length > 0) {
    sections.push(`### ℹ️ Info (${infos.length})`);
    sections.push('<details open>');
    sections.push("<summary>View info</summary>\n");
    for (const f of infos) {
      const location = f.file ? ` (${escapeMarkdown(f.file)})` : "";
      sections.push(`- **${escapeMarkdown(f.category)}** - ${escapeMarkdown(f.message)}${location}`);
    }
    sections.push("\n</details>\n");
  }

  return sections.join("\n");
}

/**
 * Renders the full markdown report suitable for GitHub PRs, Notion, and documentation
 */
export function renderMarkdownReport(report: RoastReport): string {
  const sections: string[] = [];

  // Header
  sections.push(`# 🔥 Roast Report: ${escapeMarkdown(report.projectName)}\n`);

  // Health Score
  sections.push(`## Health Score: ${report.health.score}/100 (${report.health.grade})\n`);
  sections.push(renderMarkdownHealthBar(report.health.score) + "\n");

  // Stats Table
  sections.push("## Project Summary\n");
  sections.push("| Metric | Value |");
  sections.push("|--------|-------|");
  sections.push(`| Files Scanned | ${report.stats.sourceFiles.toLocaleString()} |`);
  sections.push(`| Total Files | ${report.stats.totalFiles.toLocaleString()} |`);
  sections.push(`| Lines of Code | ${report.stats.totalLines.toLocaleString()} |`);
  sections.push(`| Dependencies | ${report.stats.dependencies} |`);
  sections.push(`| Dev Dependencies | ${report.stats.devDependencies} |\n`);

  // Findings
  sections.push(renderMarkdownFindings(report.findings));

  // Roasts
  if (report.roasts.length > 0) {
    sections.push("## 🔥 Roasts\n");
    for (const roast of report.roasts) {
      sections.push(`> **${escapeMarkdown(roast.target)}**`);
      sections.push(`> ${escapeMarkdown(roast.message)}\n`);
    }
  }

  // Fix suggestions
  if (report.fixes && report.fixes.length > 0) {
    sections.push("## 📝 Fix Suggestions\n");
    sections.push("<details>");
    sections.push("<summary>View actionable fixes</summary>\n");
    for (const fix of report.fixes) {
      const target = fix.finding.file || fix.finding.category;
      sections.push(`- **${escapeMarkdown(target)}** - ${escapeMarkdown(fix.suggestion)}`);
    }
    sections.push("\n</details>\n");
  }

  // Verdict
  sections.push("## Verdict\n");
  sections.push(escapeMarkdown(report.verdict) + "\n");

  // Footer
  sections.push("---");
  sections.push("*Generated by [roast-my-codebase](https://github.com/your-username/roast-my-codebase)*");

  return sections.join("\n");
}
