import https from 'https';
import fs from 'fs';
import { RoastReport } from '../types/index.js';

export interface PRCommentConfig {
  token: string;
  repo: string; // "owner/repo"
  prNumber: number;
}

export function detectPRContext(): PRCommentConfig | null {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY;
  const eventPath = process.env.GITHUB_EVENT_PATH;

  if (!token || !repo || !eventPath) {
    return null;
  }

  let prNumber: number | null = null;

  try {
    const raw = fs.readFileSync(eventPath, 'utf-8');
    const event = JSON.parse(raw);
    if (
      event &&
      typeof event === 'object' &&
      event.pull_request &&
      typeof event.pull_request.number === 'number'
    ) {
      prNumber = event.pull_request.number;
    }
  } catch {
    return null;
  }

  if (prNumber === null) {
    return null;
  }

  return { token, repo, prNumber };
}

function gradeEmoji(grade: string): string {
  const letter = grade.charAt(0).toUpperCase();
  if (letter === 'A') return '✅';
  if (letter === 'B') return '🟢';
  if (letter === 'C') return '🟡';
  if (letter === 'D') return '🟠';
  return '🔴';
}

function healthBar(score: number): string {
  const width = 30;
  const filled = Math.round((score / 100) * width);
  const empty = width - filled;
  return `[${('█').repeat(filled)}${('░').repeat(empty)}] ${score}/100`;
}

function formatLines(lines: number): string {
  if (lines >= 1000) {
    return `${Math.round(lines / 1000)}k`;
  }
  return String(lines);
}

const MARKER = '<!-- roast-my-codebase -->';

export function formatPRComment(report: RoastReport): string {
  const { health, stats, findings, roasts, verdict } = report;
  const emoji = gradeEmoji(health.grade);

  const lines: string[] = [];

  // 1. Header
  lines.push(`## 🔥 Roast My Codebase — Health: ${health.score}/100 ${emoji}`);
  lines.push('');

  // 2. Health bar
  lines.push(healthBar(health.score));
  lines.push('');

  // 3. Stats table
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Files  | ${stats.sourceFiles.toLocaleString()} |`);
  lines.push(`| Lines  | ${formatLines(stats.totalLines)} |`);
  lines.push(`| Deps   | ${stats.dependencies} |`);
  lines.push('');

  // 4. Findings summary
  const criticals = findings.filter(f => f.severity === 'critical');
  const warnings = findings.filter(f => f.severity === 'warning');
  const infos = findings.filter(f => f.severity === 'info');

  const summaryParts: string[] = [];
  if (criticals.length > 0) summaryParts.push(`🔴 ${criticals.length} critical`);
  if (warnings.length > 0) summaryParts.push(`⚠️ ${warnings.length} warnings`);
  if (infos.length > 0) summaryParts.push(`ℹ️ ${infos.length} info`);

  if (summaryParts.length > 0) {
    lines.push(summaryParts.join('  '));
    lines.push('');
  }

  // 5. Top findings (up to 8 critical+warning)
  const topFindings = [...criticals, ...warnings].slice(0, 8);
  if (topFindings.length > 0) {
    for (const finding of topFindings) {
      const icon = finding.severity === 'critical' ? '🔴' : '⚠️';
      const fileRef = finding.file ? `\`${finding.file}\` — ` : '';
      lines.push(`- ${icon} ${fileRef}${finding.message}`);
    }
    lines.push('');
  }

  // 6. Roasts (up to 3)
  const topRoasts = roasts.slice(0, 3);
  if (topRoasts.length > 0) {
    for (const roast of topRoasts) {
      lines.push(`> 🔥 **${roast.target}**: ${roast.message}`);
    }
    lines.push('');
  }

  // 7. Verdict
  lines.push(`*${verdict}*`);
  lines.push('');

  // 8. Footer with marker
  lines.push(
    `<sub>Generated by [roast-my-codebase](https://github.com/rahuldk1105/roast-my-codebase) · [View full report](#)</sub>`
  );
  lines.push(MARKER);

  const comment = lines.join('\n');

  // Enforce GitHub's 65,000 char limit
  if (comment.length > 65000) {
    const truncated = comment.slice(0, 64900);
    return truncated + '\n\n*…comment truncated to fit GitHub limits…*\n' + MARKER;
  }

  return comment;
}

function githubRequest(
  method: string,
  path: string,
  token: string,
  body?: unknown
): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : undefined;
    const req = https.request(
      {
        hostname: 'api.github.com',
        path,
        method,
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'User-Agent': 'roast-my-codebase',
          'Content-Type': 'application/json',
          ...(data ? { 'Content-Length': Buffer.byteLength(data) } : {}),
        },
      },
      res => {
        let raw = '';
        res.on('data', (chunk: Buffer) => (raw += chunk));
        res.on('end', () => {
          try {
            resolve(JSON.parse(raw));
          } catch {
            resolve(raw);
          }
        });
      }
    );
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

export async function postPRComment(
  report: RoastReport,
  config: PRCommentConfig
): Promise<void> {
  const { token, repo, prNumber } = config;
  const body = formatPRComment(report);

  // Check for existing comment
  let existingCommentId: number | null = null;

  try {
    const comments = (await githubRequest(
      'GET',
      `/repos/${repo}/issues/${prNumber}/comments`,
      token
    )) as Array<{ id: number; body: string }>;

    if (Array.isArray(comments)) {
      const found = comments.find(
        c => typeof c.body === 'string' && c.body.includes(MARKER)
      );
      if (found) {
        existingCommentId = found.id;
      }
    }
  } catch (err) {
    // Network error fetching comments — fall through to create a new one
    console.error('roast-my-codebase: failed to list PR comments:', err);
  }

  try {
    if (existingCommentId !== null) {
      // Update existing comment
      await githubRequest(
        'PATCH',
        `/repos/${repo}/issues/comments/${existingCommentId}`,
        token,
        { body }
      );
    } else {
      // Create new comment
      await githubRequest(
        'POST',
        `/repos/${repo}/issues/${prNumber}/comments`,
        token,
        { body }
      );
    }
  } catch (err) {
    throw new Error(
      `roast-my-codebase: failed to post PR comment: ${err instanceof Error ? err.message : String(err)}`
    );
  }
}
